/** IPC channel names shared between main, preload, and renderer. */
export const IPC = {
  // renderer -> main (invoke)
  getDoc: 'doc:get',
  saveDoc: 'doc:save',
  updateReview: 'doc:update-review',
  updateDiscussion: 'doc:update-discussion',
  submitReview: 'doc:submit-review',
  cancelReview: 'doc:cancel-review',
  openFileDialog: 'app:open-file-dialog',
  openPath: 'app:open-path',
  newWindow: 'app:new-window',
  gitInit: 'doc:git-init',
  gitLog: 'doc:git-log',
  gitRestore: 'doc:git-restore',
  reloadDoc: 'doc:reload',
  getWorkspace: 'workspace:get',
  getRecents: 'app:get-recents',
  openExternal: 'app:open-external',
  openFolderDialog: 'app:open-folder-dialog',
  openInWindow: 'workspace:open-in-window',
  readProposal: 'proposal:read',
  acceptProposal: 'proposal:accept',
  rejectProposal: 'proposal:reject',
  setupMessage: 'setup:message',
  createProject: 'setup:create-project',
  getProjectsDir: 'setup:get-projects-dir',
  getAppSettings: 'settings:get',
  chooseProjectsDir: 'settings:choose-projects-dir',
  gdocsStatus: 'gdocs:status',
  gdocsConnect: 'gdocs:connect',
  gdocsCancelConnect: 'gdocs:cancel-connect',
  gdocsDisconnect: 'gdocs:disconnect',
  gdocsImportClient: 'gdocs:import-client',
  gdocsSyncState: 'gdocs:sync-state',
  gdocsShareCreate: 'gdocs:share-create',
  gdocsPushDoc: 'gdocs:push-doc',
  gdocsPullDoc: 'gdocs:pull-doc',
  gdocsUnlink: 'gdocs:unlink',
  gdocsReplyOnDoc: 'gdocs:reply-on-doc',
  gdocsResolveOnDoc: 'gdocs:resolve-on-doc',
  openUrl: 'app:open-url',

  // renderer -> main (send)
  caretContext: 'doc:caret-context',

  // main -> renderer (send)
  docLoaded: 'doc:loaded',
  reviewUpdated: 'doc:review-updated',
  discussionUpdated: 'doc:discussion-updated',
  docChangedOnDisk: 'doc:changed-on-disk',
  agentStatus: 'agent:status',
  agentActivity: 'agent:activity',
  menuSave: 'menu:save',
  menuSubmit: 'menu:submit',
  menuTogglePreview: 'menu:toggle-preview',
  menuAddComment: 'menu:add-comment',
  menuFormatTable: 'menu:format-table',
  menuOpenSettings: 'menu:open-settings',
  gdocsAuthChanged: 'gdocs:auth-changed',
  gdocsSyncChanged: 'gdocs:sync-changed',
} as const;
