import { describe, expect, it } from 'vitest';
import { displaySize, minimalPng, pngDimensions, resolveImageSource } from '../src/images.ts';
import { buildSegment } from '../src/builder.ts';
import { docToBlocks } from '../src/reader.ts';
import { identity } from '../src/blocks.ts';
import { markdownToBlocks } from '../src/markdown.ts';
import type { GDocDocument } from '../src/gdoc.ts';

type Req = Record<string, any>;

describe('UIMG — image logic (offline)', () => {
  it('UIMG-5: URLs and data URIs pass through; relative paths resolve; empty → null', () => {
    expect(resolveImageSource('https://x.dev/i.png', '/docs')).toEqual({ kind: 'uri', uri: 'https://x.dev/i.png' });
    expect(resolveImageSource('data:image/png;base64,AAAA', '/docs')).toEqual({ kind: 'uri', uri: 'data:image/png;base64,AAAA' });
    expect(resolveImageSource('img/pic.png', '/home/drew/doc')).toEqual({ kind: 'file', path: '/home/drew/doc/img/pic.png' });
    expect(resolveImageSource('../pic.png', '/home/drew/doc')).toEqual({ kind: 'file', path: '/home/drew/pic.png' });
    expect(resolveImageSource('', '/docs')).toBeNull();
  });

  it('UIMG-6: PNG dimensions parse from generated bytes; garbage → null', () => {
    const png = minimalPng(320, 200);
    expect(pngDimensions(png)).toEqual({ width: 320, height: 200 });
    expect(pngDimensions(new Uint8Array([1, 2, 3, 4]))).toBeNull();
  });

  it('display size clamps to page width and max height, respects DPI', () => {
    expect(displaySize(400, 300)).toEqual({ widthPt: 300, heightPt: 225 }); // 96dpi: ×0.75
    expect(displaySize(400, 300, 192)).toEqual({ widthPt: 150, heightPt: 113 }); // @2x halves
    const wide = displaySize(2000, 500);
    expect(wide.widthPt).toBe(468);
    expect(wide.heightPt).toBe(117);
    const tall = displaySize(500, 4000);
    expect(tall.heightPt).toBe(600);
  });

  it('UIMG-1: an inline object advances the index by exactly 1 unit', () => {
    const images = new Map([['u.png', { uri: 'https://x.dev/u.png', widthPt: 100, heightPt: 80 }]]);
    const { requests } = buildSegment(
      [
        { kind: 'image', src: 'u.png', alt: '', figure: false },
        { kind: 'paragraph', spans: [{ text: 'after' }] },
      ],
      1,
      { images },
    ) as { requests: Req[] };
    const img = requests.find((r) => r.insertInlineImage);
    expect(img!.insertInlineImage.objectSize.width.magnitude).toBe(100);
    // Image paragraph = image (1) + newline (1) → next insert at 3.
    const after = requests.filter((r) => r.insertText).find((r) => r.insertText.text === 'after\n');
    expect(after!.insertText.location.index).toBe(3);
  });

  it('UIMG-3: figure emission — image centered, caption present/italic/centered', () => {
    const images = new Map([['f.png', { uri: 'https://x.dev/f.png' }]]);
    const { requests } = buildSegment(
      [{ kind: 'image', src: 'f.png', alt: 'A caption', figure: true }],
      1,
      { images },
    ) as { requests: Req[] };
    const centers = requests.filter((r) => r.updateParagraphStyle?.paragraphStyle?.alignment === 'CENTER');
    expect(centers).toHaveLength(2); // image paragraph + caption paragraph
    const italic = requests.find((r) => r.updateTextStyle?.textStyle?.italic && r.updateTextStyle?.fields?.includes('fontSize'));
    expect(italic).toBeDefined();
    expect(requests.some((r) => r.insertText?.text === 'A caption\n')).toBe(true);
  });

  it('UIMG-4: an unstaged image degrades to a placeholder paragraph without corrupting indices', () => {
    const { requests } = buildSegment(
      [
        { kind: 'image', src: 'missing.png', alt: 'x', figure: true },
        { kind: 'paragraph', spans: [{ text: 'after' }] },
      ],
      1,
      { images: new Map([['missing.png', null]]) },
    ) as { requests: Req[] };
    expect(requests.some((r) => r.insertInlineImage)).toBe(false);
    const after = requests.filter((r) => r.insertText).find((r) => r.insertText.text === 'after\n');
    expect(after!.insertText.location.index).toBe(2); // placeholder '\n' only
  });

  it('reader folds image + centered-italic caption back into a figure; identity matches md side', () => {
    const doc: GDocDocument = {
      inlineObjects: {
        obj1: { inlineObjectProperties: { embeddedObject: { imageProperties: { contentUri: 'https://goog/x' } } } },
      },
      body: {
        content: [
          {
            startIndex: 1,
            endIndex: 3,
            paragraph: {
              elements: [{ inlineObjectElement: { inlineObjectId: 'obj1' } }, { textRun: { content: '\n' } }],
              paragraphStyle: { namedStyleType: 'NORMAL_TEXT', alignment: 'CENTER' },
            },
          },
          {
            startIndex: 3,
            endIndex: 13,
            paragraph: {
              elements: [{ textRun: { content: 'A caption\n', textStyle: { italic: true } } }],
              paragraphStyle: { namedStyleType: 'NORMAL_TEXT', alignment: 'CENTER' },
            },
          },
        ],
      },
    };
    const blocks = docToBlocks(doc).map((r) => r.block);
    expect(blocks).toHaveLength(1);
    expect(blocks[0]).toMatchObject({ kind: 'image', figure: true, alt: 'A caption' });
    const mdSide = markdownToBlocks('![A caption](local/path.png)\n');
    expect(identity(blocks[0]!)).toBe(identity(mdSide[0]!)); // src excluded from identity
  });
});

describe('staging machinery, offline half (issue #18)', () => {
  it('jpegDimensions parses an SOF0 fragment; imageDimensions dispatches', async () => {
    const { jpegDimensions, imageDimensions, buildImagesDocx } = await import('../src/images.ts');
    // Handcrafted: SOI, APP0 (16 bytes), SOF0 with height 200 / width 320.
    const jpeg = new Uint8Array([
      0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10, ...new Array(14).fill(0),
      0xff, 0xc0, 0x00, 0x11, 0x08, 0x00, 0xc8, 0x01, 0x40, 0x03, ...new Array(10).fill(0),
    ]);
    expect(jpegDimensions(jpeg)).toEqual({ width: 320, height: 200 });
    expect(imageDimensions(minimalPng(10, 20))).toEqual({ width: 10, height: 20 });
    expect(imageDimensions(new Uint8Array([1, 2, 3]))).toBeNull();

    // The docx is a valid stored zip: PK signature, end-of-central marker.
    const docx = buildImagesDocx([{ bytes: minimalPng(5, 5), ext: 'png' }]);
    expect([...docx.slice(0, 4)]).toEqual([0x50, 0x4b, 0x03, 0x04]);
    const tail = docx.slice(-22, -18);
    expect([...tail]).toEqual([0x50, 0x4b, 0x05, 0x06]);
    const text = new TextDecoder('latin1').decode(docx);
    expect(text).toContain('word/media/img1.png');
    expect(text).toContain('rIdImg1');
  });
});
